name: metadata_web
description: A powerful web-specific metadata extraction implementation for Flutter, seamlessly integrating with web browsers to extract EXIF and media data.
version: 0.0.1
publish_to: 'none'
repository: https://github.com/Dinesh-DLanzer/metadata_web
issue_tracker: https://github.com/Dinesh-DLanzer/metadata_web/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  metadata_core:
    path: ../metadata_core
  js: ^0.6.7
  web: ^1.0.0
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
